# Generated by Django 2.1 on 2018-09-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('reference', models.CharField(max_length=100, verbose_name='Referencia')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('text_article', models.TextField(blank=True, verbose_name='Texto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data da Publicacao')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/imgs', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Artigo',
            },
        ),
    ]
