# Generated by Django 2.1 on 2018-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AddField(
            model_name='article',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Atalho'),
        ),
    ]
