# Generated by Django 2.1 on 2018-09-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180913_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
